version: 2

models:

  - name: stg_league
    columns:
      - name: league_id
        tests: [not_null]
      - name: season
        tests: [not_null]
      - name: ingested_at
        tests: [not_null]
      - name: country_name
        tests: [not_null]
      - name: country_code
        tests: [not_null]
      - name: season_start_date
        tests: [not_null]
      - name: season_end_date
        tests: [not_null]

      
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - league_id
              - season
      - dbt_utils.expression_is_true:
          expression: "season_start_date <= season_end_date"      
      - dbt_utils.expression_is_true:
          expression: "country_code is null or regexp_like(country_code, '^[A-Z]{2}$')"
      
      
  - name: stg_teams_info
    columns:
      - name: league_id
        tests: [not_null]
      - name: season
        tests: [not_null]
      - name: ingested_at
        tests: [not_null]
      - name: team_id
        tests: [not_null]
      - name: team_name
        tests: [not_null]
      - name: team_founded
        tests: [not_null]
      - name: venue_id
        tests: [not_null]
      - name: venue_name
        tests: [not_null]
      - name: venue_capacity
        tests: [not_null]        
      
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [league_id, team_id,season]  
      
  
  - name: stg_fixture_statistics
    columns:
      - name: ingested_at
        description: "Ingestion timestamp."
        tests:
          - not_null

      - name: league_id
        tests:
          - not_null

      - name: season
        tests:
          - not_null

      - name: fixture_id
        tests:
          - not_null
          # Uncomment if you have a fixtures model/table
          # - relationships:
          #     to: ref('stg_fixtures')
          #     field: fixture_id

      - name: team_id
        tests:
          - not_null
          # Uncomment if you have a teams model/table
          # - relationships:
          #     to: ref('stg_teams_info')
          #     field: team_id

      - name: team_name
        tests:
          - not_null

      - name: team_logo_url
        tests:
          - not_null

    
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - league_id
              - season
              - fixture_id
              - team_id

      - dbt_utils.expression_is_true:
          arguments:
            expression: "ball_possession_pct is null or (ball_possession_pct >= 0 and ball_possession_pct <= 100)"

      - dbt_utils.expression_is_true:
          arguments:
            expression: "passes_pct is null or (passes_pct >= 0 and passes_pct <= 100)"                  

  - name: stg_fixture_info
    columns:
      - name: api_fixture_id
        tests:
          - not_null
      - name: league_id
        tests:
          - not_null
      - name: season
        tests:
          - not_null
      - name: fixture_date_utc
        tests:
          - not_null
      - name: fixture_timezone
        tests:
          - not_null
      - name: status_short
        tests:
          - not_null
      - name: status_long
        tests:
          - not_null
      - name: venue_id
        tests:
          - not_null
      - name: venue_name
        tests:
          - not_null
      - name: home_team_id
        tests:
          - not_null
      - name: away_team_id
        tests:
          - not_null
      - name: payload_response
        tests:
          - not_null
          
    tests:
    - dbt_utils.unique_combination_of_columns:
        arguments:
          combination_of_columns:
            - league_id
            - season
            - payload_response

  - name: stg_team_statistics

    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns: [league_id, season, team_id, ingested_at]

    columns:
      - name: ingested_at
        tests: [not_null]

      - name: league_id
        tests: [not_null]

      - name: season
        tests: [not_null]

      - name: team_id
        tests: [not_null]

      - name: fixtures_played_total
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: true
              where: "fixtures_played_total is not null"

      - name: goals_for_total
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: true
              where: "goals_for_total is not null"

      - name: goals_against_total
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: true
              where: "goals_against_total is not null"

  - name: stg_fixture_line_up
    description: >
      Staging model for fixture lineups.
      One row per fixture_id + team_id.
      start_xi_json and substitutes_json are kept as VARIANT arrays.

    columns:

      - name: ingested_at
        tests: [not_null]

      - name: league_id
        tests: [not_null]

      - name: season
        tests: [not_null]

      - name: fixture_id
        tests: [not_null]

      - name: team_id
        tests: [not_null]

      - name: formation
        tests: [not_null]

    tests:
      - dbt_utils.expression_is_true:
          arguments:
            expression: "array_size(start_xi_json) = 11"

      - dbt_utils.expression_is_true:
          arguments:
            expression: "array_size(substitutes_json) >= 0"

  - name: stg_fixture_predictions
    description: >
      Staging model for fixture predictions.
      One row per fixture_id.
      Predictions are kept as VARIANT.
    columns:
      - name: ingested_at
        tests:
          - not_null

      - name: league_id
        tests:
          - not_null

      - name: season
        tests:
          - not_null

      - name: fixture_id
        tests:
          - not_null

      - name: team_home_id
        tests:
          - not_null
      - name: team_away_id
        tests:
          - not_null
      - name: advice
        tests:
          - not_null


    tests:

      - dbt_utils.expression_is_true:
          arguments:
            expression: "PERCENT_AWAY is null or (PERCENT_AWAY >= 0 and PERCENT_AWAY <= 100) "

      - dbt_utils.expression_is_true:
          arguments:
            expression: "PERCENT_HOME is null or (PERCENT_HOME >= 0 and PERCENT_HOME <= 100) "

      - dbt_utils.expression_is_true:
          arguments:
            expression: "PERCENT_DRAW is null or (PERCENT_DRAW >= 0 and PERCENT_DRAW <= 100) "

  # ✅ Sum must equal 100 (when all three are present)
      - dbt_utils.expression_is_true:
          arguments:
            expression: >
              (
                PERCENT_AWAY is null
                or PERCENT_HOME is null
                or PERCENT_DRAW is null
                or (PERCENT_AWAY + PERCENT_HOME + PERCENT_DRAW between 99 and 101)
              )

      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - league_id
              - season
              - fixture_id
          severity: warn

  - name: stg_player_trophies

    columns:
      - name: league_id
        tests:
          - not_null
      - name: player_id
        tests:
          - not_null
      - name: trophy_1_league
        tests:
          - not_null
      - name: trophy_1_place
        tests:
          - not_null

      - name: payload_json
        tests:
          - not_null

    tests:

      # Ensure player has no exact duplicate trophies
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - player_id
              - trophy_1_league
              - trophy_1_place
              - trophy_1_season

      # Optional: season format check (allow null)
      - dbt_utils.expression_is_true:
          arguments:
            expression: >
              (
                trophy_1_league is not null
                and trophy_1_season is not null
              )

  - name: stg_players_statistics
    columns:

      - name: player_id
        tests:
          - not_null

      - name: league_id
        tests:
          - not_null

      - name: season
        tests:
          - not_null

      - name: team_id
        tests:
          - not_null
      # JSON existence sanity checks
      - name: games_json
        tests:
          - not_null

      - name: goals_json
        tests:
          - not_null

      - name: passes_json
        tests:
          - not_null

    tests:
      - dbt_utils.expression_is_true:
          arguments:
            expression: "player_age is null or player_age between 15 and 50"

      - dbt_utils.expression_is_true:
          arguments:
            expression: "player_photo_url is null or player_photo_url like 'https:%'"
